### PR TITLE
Add Geospatial sample on anonymizing geohashes

### PR DESCRIPTION
**Pull request by brandtol**
This sample shows how to anonymize geohashes produced by the Geospatial toolkit Hangout operator.
It implements the following processing steps :

1) simulate location data for 6 different entities
2) detect hangout areas for the entities, resulting in 6 character geohashes
3) anonymize the calculated geohashes using a secret key and a crypto hash function
4) aggregate the number of entities per anonymized geohash and print the resulting numbers

### CODE REVIEW

**Comment by chanskw** [comment]
Can you please add copyrights to the sample before we pull this in?  Thanks!

**Comment by brandtol** [comment]
Added the header.

**Comment by ddebrunner** [comment]
A short definition of what it means to anonymize geohashes would be useful in the sample.

Nothing came up in a quick google search. I can guess, but the purpose of a sample is to teach.

**Comment by brandtol** [comment]
@ddebrunner A streamsdev article about this sample is in the works. I will add a link to the article and improve the readme, when available.

**Pull request merged**
