### PR TITLE
new Database sample for Teradata 

### PR DESCRIPTION
**Pull request by anouri**
New Database sample for Teradata

### CODE REVIEW

**Comment by anouri** [comment]
In README.md, the IBM InfoSphere Streams changed to IBM Streams.
The copyrights changed from  2014,2016 to 2017

—

**Comment by chanskw** [comment]
@natashadsilva please consider adding this to Samples Repository

**Comment by natashadsilva** [comment]
@anouri Thank you for the well documented contribution.  Just a quick question, the README mentions they need unixODBC..but is it installed withe the Teradata client? Is it something most people have or would it be helpful to add instructions?
I changed this line: "The following document describes how to connect to a Teradata database via Streams toolkit com.ibm.streams.dbtoolkit.db" to "com.ibm.streams.db" ..I think that is correct, right?

**Comment by anouri** [comment]
@natashadsilva Thank you for your review comments.
The unixODBC is not a part of Teradata client.
The README file has been updated with a new section "Installation and configuration of unixODBC" 
https://github.com/IBMStreams/samples/pull/70

**Pull request merged**
